name: CI
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

env:
  CARGO_TERM_COLOR: always
  RUST_TARGET: x86_64-unknown-linux-musl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      uses: gmiam/rust-musl-action@master
      with:
        args: make all
